CREATE DATABASE CinemaDb

USE CinemaDb

CREATE TABLE Movies(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Duration INT
)

CREATE TABLE Genres(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100)
)

CREATE TABLE MovieGenres(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieId FOREIGN KEY REFERENCES Movies(Id),
	GenreId INT CONSTRAINT FK_GenreId FOREIGN KEY REFERENCES Genres(Id)
)

CREATE TABLE Acters(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Surname NVARCHAR(120)
)

CREATE TABLE MovieActers(
	Id INT PRIMARY KEY IDENTITY,
	MovieId INT CONSTRAINT FK_MovieActersId FOREIGN KEY REFERENCES Movies(Id),
	ActerId INT CONSTRAINT FK_AcrterId FOREIGN KEY REFERENCES Acters(Id)
)

CREATE TABLE Halls(
	Id INT PRIMARY KEY IDENTITY,
	Name NVARCHAR(100),
	Seats INT
)

CREATE TABLE Sessions(
	Id INT PRIMARY KEY IDENTITY,
	[Start] DATETIME2,
	[End] DATETIME2,
	MovieId INT CONSTRAINT FK_MovieSessionId FOREIGN KEY REFERENCES Movies(Id),
	HallId INT CONSTRAINT FK_SessionHallId FOREIGN KEY REFERENCES Halls(Id)
)

CREATE TABLE Customers(
	Id INT PRIMARY KEY IDENTITY,
	Fullname NVARCHAR(100),
	PhoneNumber NVARCHAR(50)
)

CREATE TABLE Tickets(
	Id INT PRIMARY KEY IDENTITY,
	[Type] NVARCHAR(100),
	Price DECIMAL(18,2),
	CustomerId INT CONSTRAINT FK_TicketCustomerId FOREIGN KEY REFERENCES Customers(Id),
	SessionId INT CONSTRAINT FK_TicketSessionId FOREIGN KEY REFERENCES Sessions(Id)
)